version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-stretch-node
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu

      - image: circleci/postgres:12.4-ram
        environment:
        - POSTGRES_USER=ubuntu

    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
