version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-stretch-node
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu

      - image: circleci/postgres:12.4-ram
        environment:
        - POSTGRES_USER=ubuntu

    executor: ruby/default
    steps:
      - checkout

      - run:
          name: "Install specified version of Node.js and npm"
          command: |
            export WANTED_NODE_VERSION=`grep nodejs .tool-versions | cut -d " " -f 2`
            echo $WANTED_NODE_VERSION
            curl -sSL "https://nodejs.org/dist/v${WANTED_NODE_VERSION}/node-v${WANTED_NODE_VERSION}-linux-x64.tar.xz" | sudo tar --strip-components=2 -xJ -C /usr/local/bin/ node-v${WANTED_NODE_VERSION}-linux-x64/bin/node
            curl https://www.npmjs.com/install.sh | sudo bash
            node -v

      - ruby/bundle-install
