version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.0.2
        environment:
        - PG_HOST=localhost
        - PG_USER=ubuntu

      - image: cimg/postgres:15.4
        environment:
        - POSTGRES_USER=ubuntu
        - POSTGRES_PASSWORD=secret

    executor: ruby/default
    steps:
      - checkout

      - node/install:
          install-yarn: true
          node-version: '16.13'

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile.lock" }}-{{checksum "yarn.lock"}}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3
            bundle clean --force
            yarn install

      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules/
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}

      - run:
          name: Set up database
          command: |
            bundle exec rails db:create db:schema:load
          environment:
            DATABASE_URL: "postgres://ubuntu:secret@localhost:5432/circle_test"
            HOST: "test.host"

      - run:
          name: Run tests
          command: |
            mkdir /tmp/test-results
            bundle exec rake
          environment:
            DATABASE_URL: "postgres://ubuntu:secret@localhost:5432/circle_test"
            HOST: "test.host"

      - run:
          name: Verify assets
          command: |
            bundle exec rails assets:precompile
          environment:
            DATABASE_URL: "postgres://ubuntu:secret@localhost:5432/circle_test"

      # collect reports
      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results
